// src/content/projects/all.ts
// project portfolio data

import type { Project } from '~/shared/types';

export const projects: Project[] = [
  {
    title: 'MDX Preview for VS Code',
    tagline:
      'Live MDX/Markdown preview extension with React component rendering and rich documentation features.',
    dateRange: 'Jan 2026 - Present',
    status: 'in-development',
    madeFor: 'Personal',
    featured: false,
    bulletPoints: [
      'Built live preview pipeline with debounced updates and bidirectional scroll sync for .mdx, .md, and TSX previews',
      'Implemented Safe vs Trusted modes with workspace trust and script execution gating for secure component rendering',
      'Added MDX 3 support with React 18, Shiki syntax highlighting, Mermaid diagrams, GitHub alert callouts, and KaTeX math',
      'Delivered configuration-driven UX (TOC, frontmatter display, white background override) and command palette actions for preview control',
    ],
    technologies: [
      'TypeScript',
      'React',
      'MDX',
      'VS Code Extension API',
      'Shiki',
      'KaTeX',
      'Mermaid',
    ],
    imagePath: '/assets/projects/images/vsc-mdx.png',
    imageAlt: 'MDX Preview for VS Code extension screenshot',
    repoUrl: 'https://github.com/ggfincke/vsc-mdx-preview',
  },
  {
    title: 'OpenCode to ccusage',
    tagline:
      'CLI tool that exports OpenCode sessions to ccusage-compatible JSONL and generates combined usage reports.',
    dateRange: 'Dec 2025',
    status: 'live',
    madeFor: 'Personal',
    featured: false,
    bulletPoints: [
      'Converted OpenCode session data into ccusage JSONL with per-project or per-directory grouping',
      'Built report workflow that merges OpenCode and Claude Code usage data for unified metrics',
      'Added export controls (since date, dry run, custom output dir, overwrite) and verbose progress logging',
      'Exposed clear CLI commands (report, export, advanced) with pass-through flags to ccusage',
    ],
    technologies: ['TypeScript', 'Node.js', 'CLI'],
    imageAlt: 'OpenCode to ccusage CLI screenshot',
    repoUrl: 'https://github.com/ggfincke/opencode-to-ccusage',
  },
  {
    title: 'Reactive Workbench',
    tagline:
      'Context-aware VS Code automation that adapts themes, panels, layouts, and editor features based on workspace state.',
    dateRange: 'Nov 2025 – Present',
    status: 'in-development',
    madeFor: 'Personal',
    featured: false,
    bulletPoints: [
      'Built rule engine with first-match-wins evaluation, overlap detection, and mode bundles for predictable, reusable automation',
      'Implemented 15+ action types (themes, panels, layout, notifications, tasks/commands, profiles) and 17+ condition types (file patterns, language, debug/test state, Git branch, time of day, diagnostics)',
      'Added diagnostics tooling to lint and test rules, explain the active rule, and surface overlap warnings with analytics/history',
      'Ensured safe, reversible changes by applying all actions through VS Code APIs with optional safe mode',
    ],
    technologies: ['TypeScript', 'Node.js', 'VS Code Extension API'],
    repoUrl: 'https://github.com/ggfincke/reactive-workbench',
  },
  {
    title: 'SwimMate v2',
    tagline:
      'Full-stack swimming platform with native iOS/watchOS apps, HealthKit sync, and AI-powered workout generation.',
    dateRange: 'Oct 2025 - Present',
    status: 'in-development',
    madeFor: 'Personal',
    featured: true,
    bulletPoints: [
      'Built Django REST API with JWT auth, OpenAPI docs, and PostgreSQL + pgvector for semantic search and workout library retrieval',
      'Implemented RAG-based workout generation using embeddings and LLM calls to personalize plans and surface curated sets',
      'Developed SwiftUI iOS/watchOS apps with HealthKit workout capture, Apple Watch live metrics, and Swift Charts analytics',
      'Added actor-based networking with token refresh, background sync, and offline-first workout tracking with secure Keychain storage',
      'Created structured workout builder and paginated swim set library with iOS-to-watch sync via WatchConnectivity',
    ],
    technologies: [
      'Swift',
      'SwiftUI',
      'watchOS',
      'HealthKit',
      'WatchConnectivity',
      'Swift Charts',
      'Django',
      'Django REST Framework',
      'PostgreSQL',
      'pgvector',
      'OpenAI',
      'JWT',
      'Python',
    ],
    imagePath: '/assets/projects/images/swimmatev2.png',
    imageAlt: 'SwimMate v2 full-stack platform screenshot',
    repoUrl: 'https://github.com/ggfincke/SwimMate',
  },
  {
    title: 'Portfolio Website v2',
    tagline:
      "The site you're on: minimalist, section‑based, and content‑driven.",
    dateRange: 'Oct 2025 – Present',
    status: 'live',
    madeFor: 'Personal',
    featured: true,
    bulletPoints: [
      'Complete redesign with Vite 7 + React 19 + TypeScript + Tailwind CSS 4.0 for pure client‑side architecture',
      'Section‑based organization: each feature isolated with its own components, content, and utilities for maximum modularity',
      'Content‑driven development: strict separation of data from presentation; content lives in dedicated files, components focus on rendering',
      'Material Theme Ocean HC color system with semantic technology categorization (100+ techs mapped)',
      'Staggered slide‑in animations with full prefers‑reduced‑motion accessibility support',
      'Type‑safe routing with React Router 7 and centralized type definitions with barrel exports',
    ],
    imagePath: '/assets/projects/images/portfoliov2.png',
    imageAlt: 'Portfolio website v2 screenshot',
    technologies: [
      'React',
      'TypeScript',
      'Vite',
      'Tailwind CSS',
      'React Router',
      'ESLint',
      'Prettier',
    ],
    repoUrl: 'https://github.com/ggfincke/fincke.dev-v2',
    liveUrl: 'https://fincke.dev',
  },
  {
    title: 'Minecart',
    tagline:
      'Discord bot for managing Minecraft servers across local Docker and AWS EC2 with multi-tenant support.',
    dateRange: 'Sep 2025 – Present',
    status: 'live',
    madeFor: 'Personal',
    featured: true,
    bulletPoints: [
      'Built interactive Discord dashboards (buttons, modals, select menus) for status, start/stop/restart, logs, backups, and configuration',
      'Implemented provider abstraction for local Docker and AWS EC2 with runtime switching, health checks, and live status via RCON and mcstatus.io',
      'Added scheduling and automation for idle shutdown, scheduled start/stop windows, crash recovery, and automated backups with retention',
      'Shipped multi-tenant controls: multi-server registration, role-based permissions (view/operate/admin/owner), channel bindings, and guild defaults',
      'Delivered world and content management (multiple worlds, staging worlds, blue-green cutovers, Modrinth mods, resource packs, version switching)',
      'Added monitoring and governance: performance metrics, audit logs, maintenance mode, usage metering/quotas, and optional S3 storage',
    ],
    technologies: [
      'TypeScript',
      'Node.js',
      'Docker',
      'Docker Compose',
      'RCON',
      'AWS',
      'EC2',
      'SSM',
      'CloudWatch',
      'S3',
      'Discord.js',
    ],
    imagePath: '/assets/projects/images/minecart.png',
    imageAlt: 'Minecart Discord bot screenshot',
  },
  {
    title: 'Hopper',
    tagline:
      'Hybrid microservices inventory system for multi‑marketplace ecommerce.',
    dateRange: 'Sep 2025 – Present',
    status: 'in-development',
    madeFor: 'Personal',
    featured: true,
    bulletPoints: [
      'Orchestrates products, listings, orders, and fees across marketplaces with Java/Spring Boot core and a Go connector service',
      'JWT auth with access/refresh tokens, role‑based authorization (ADMIN/USER/API CLIENT), secure rotation, and Spring Security guards',
      'AES‑GCM‑256 credential encryption with PBKDF2 key derivation and versioned encryption metadata for rotation',
      'Normalized PostgreSQL schema (13 Flyway migrations), foreign keys, composite uniques, and performance indexes',
      'Order state machine (pending→confirmed→paid→processing→shipped→delivered) with business rules and stock management',
      'Spring Batch background jobs for order import & synchronization via MarketplaceClient abstraction',
      'OpenAPI 3.1 spec for the Go connector (idempotency, error taxonomy) and Bruno/CI collections for contract tests',
    ],
    technologies: [
      'Java',
      'Spring Boot',
      'Spring Data JPA',
      'PostgreSQL',
      'Flyway',
      'H2',
      'Spring Security',
      'Spring Batch',
      'Actuator',
      'Gradle',
      'Go',
    ],
    // todo restore hopper screenshot asset once export is ready
    imageAlt: 'Hopper inventory management system screenshot',
    repoUrl: 'https://github.com/ggfincke/hopper',
  },
  {
    title: 'Loom',
    tagline:
      'AI-powered resume tailoring CLI with structured edits, diff review, and versioned workflows.',
    dateRange: 'Aug 2025 – Present',
    status: 'live',
    madeFor: 'Personal',
    featured: true,
    bulletPoints: [
      'Built Typer-based command suite (sectionize, tailor, generate, apply) with configurable defaults and themed help UI',
      'Implemented structured JSON edit pipeline with interactive diff resolution, risk/on-error policies, and format-preserving DOCX/LaTeX/Typst handling',
      'Integrated multi-provider AI (OpenAI, Anthropic, Gemini, Mistral, Ollama, LM Studio) with model selection and response caching',
      'Added snapshot-based version management with restore and comparison tooling for safe iteration',
      'Shipped ATS compatibility checks, bulk job processing with comparison matrices, and exports to txt/pdf/html',
    ],
    technologies: [
      'Python',
      'Typer',
      'Rich',
      'OpenAI',
      'Anthropic',
      'Gemini',
      'Mistral',
      'Ollama',
      'LM Studio',
      'DOCX',
      'LaTeX',
      'Typst',
      'JSON',
      'CLI',
    ],
    imagePath: '/assets/projects/images/loom.png',
    imageAlt: 'Loom app screenshot',
    repoUrl: 'https://github.com/ggfincke/loom',
  },
  {
    title: 'TrackBasket',
    tagline: 'AI‑assisted price tracking for 30k+ products across retailers.',
    dateRange: 'May 2025 - Present',
    status: 'live',
    madeFor: 'Bolt Hackathon',
    featured: true,
    bulletPoints: [
      'Chat‑to‑basket turns natural language into structured baskets using Supabase and OpenAI',
      'Advanced crawling with CAPTCHA handling, anti‑bot countermeasures, normalization, and real‑time updates',
      'Backend: Edge Functions, PostgreSQL fuzzy search, UPC matching, and event‑driven notifications',
      'AI‑powered matching with intelligent alternatives and cross‑retailer price correlation via UPC',
      'Granular alerts for price drops, availability changes, and product updates; collaborative basket management',
      'Responsive UI with price history charts and recommendations',
    ],
    imagePath: '/assets/projects/images/trackbasket.png',
    imageAlt: 'TrackBasket app screenshot',
    technologies: [
      'TypeScript',
      'Python',
      'Supabase',
      'Next.js',
      'React',
      'OpenAI',
      'PostgreSQL',
      'Docker',
      'Swift',
    ],
    repoUrl: 'https://github.com/ggfincke/BoltHackathon',
  },
  {
    title: 'Portfolio Website v1',
    tagline:
      'Previous Next.js portfolio site, now retired and superseded by v2.',
    dateRange: 'Mar 2025 - Sep 2025',
    status: 'complete',
    madeFor: 'Personal',
    featured: false,
    bulletPoints: [
      'Next.js + TypeScript + Tailwind; responsive UI with subtle motion',
      'Custom component system, accessibility and performance‑first design',
      'CI/CD with Vercel deploys, Lighthouse CI checks, and automated prereleases/tags',
      "Retired in favor of v2's simpler, client-side architecture",
    ],
    imagePath: '/assets/projects/images/portfolio.png',
    imageAlt: 'Portfolio website v1 screenshot',
    technologies: [
      'Next.js',
      'TypeScript',
      'Tailwind CSS',
      'GitHub Actions',
      'CI/CD',
      'Figma',
    ],
    repoUrl: 'https://github.com/ggfincke/fincke.dev',
  },
  {
    title: 'InStock',
    tagline: 'High‑frequency stock & price tracker; precursor to TrackBasket.',
    dateRange: 'Dec 2024 - Mar 2025',
    status: 'paused',
    madeFor: 'Personal',
    bulletPoints: [
      'Optimized detection for restocks and price changes on high‑velocity products',
      'Django + PostgreSQL core with Redis/Celery microservices and Selenium scraping',
      'REST API for React/Swift clients; Discord notifications via Discord.py',
    ],
    technologies: [
      'Python',
      'Django',
      'PostgreSQL',
      'Selenium',
      'Redis',
      'Celery',
      'React',
      'Swift',
      'Discord.py',
    ],
    repoUrl: 'https://github.com/ggfincke/instock',
  },
  {
    title: 'Deep Learning Architecture Comparison & Analysis for CIFAR-10',
    tagline: 'DenseNet121 vs CNN/ResNet50/RFM on CIFAR‑10.',
    collaborators: [
      { name: 'Jacob Goulet' },
      { name: 'Tyler Rossi' },
      { name: 'Diego Bueno' },
      { name: 'Javier Pozo Miranda' },
      { name: 'Duong Bao' },
    ],
    dateRange: 'Nov 2024 – Dec 2024',
    status: 'complete',
    madeFor: 'Penn State',
    bulletPoints: [
      'DenseNet121 topped at 74% test accuracy vs CNN 69%, RFM 51.6%, ResNet50 47%',
      'Documented optimization challenges, loss/accuracy curves, and future work; full metric suite and confusion matrices',
    ],
    imagePath: '/assets/projects/images/452final.png',
    imageAlt: 'MATH 452 Final Report screenshot',
    technologies: [
      'Python',
      'TensorFlow',
      'Keras',
      'NumPy',
      'pandas',
      'matplotlib',
      'seaborn',
      'scikit-learn',
      'Deep Learning',
      'CNN',
      'ResNet',
      'DenseNet',
      'LaTeX',
      'Random Fourier Features',
    ],
    repoUrl: 'https://github.com/ggfincke/MATH452_projects',
    liveUrl: '/assets/projects/documents/MATH_452_-_Final_Report.pdf',
  },
  {
    title: 'Computer Architecture Projects',
    tagline:
      'Cache/memory exploration and branch‑prediction analysis on SimpleScalar.',
    dateRange: 'Sep 2024 – Dec 2024',
    status: 'complete',
    madeFor: 'Penn State',
    bulletPoints: [
      'Framework to explore multi‑dimensional cache/memory configs with automated validation and evaluation across benchmarks',
      'Branch predictors: static, 1‑bit/2‑bit, bimodal, gshare, and hybrid with chooser; accuracy and misprediction analysis',
      'Detailed reports with quantitative trade‑offs and recommendations',
    ],
    technologies: [
      'C/C++',
      'SimpleScalar',
      'Python',
      'Cache Hierarchies',
      'Branch Prediction',
      'Performance Analysis',
    ],
    repoUrl: 'https://github.com/ggfincke/CMPEN431_projects',
  },
  {
    title: 'TCGhub',
    tagline: 'TCGplayer‑style marketplace clone with hand‑rolled SQL.',
    collaborators: [{ name: 'Yash Tumuluri' }],
    dateRange: 'Sep 2024 - Dec 2024',
    status: 'complete',
    madeFor: 'Penn State',
    featured: false,
    bulletPoints: [
      'React marketplace with live data integration and custom SQLite schema in BCNF',
      'Hand‑written SQL queries, filtering/search for sets & rarities, responsive UI (scored >100%)',
    ],
    imagePath: '/assets/projects/images/tcghub2.png',
    imageAlt: 'TCGhub app screenshot',
    technologies: ['React', 'SQL', 'Python', 'SQLite', 'Node.js'],
    repoUrl: 'https://github.com/ggfincke/TCGhub',
  },
  {
    title: 'Traditional Machine Learning Methods Exploration for MNIST',
    tagline: 'Classical ML baselines for MNIST with KNN/LR/SVM.',
    dateRange: 'Sep 2024 - Oct 2024',
    status: 'complete',
    madeFor: 'Penn State',
    bulletPoints: [
      'KNN 94.4%, Logistic Regression 91.1%, SVM (RBF) 95.3% on a 10k‑image subset; precision/recall/F1 with confusion matrices',
      'Preprocessing: normalization to [0,1], 784‑D flattening, stratified train/test; K‑Means + PCA for unsupervised analysis (100% grade)',
    ],
    imagePath: '/assets/projects/images/452midterm.png',
    imageAlt: 'MATH 452 Midterm Report screenshot',
    technologies: [
      'Python',
      'scikit-learn',
      'NumPy',
      'pandas',
      'matplotlib',
      'seaborn',
      'Machine Learning',
      'LaTeX',
    ],
    repoUrl: 'https://github.com/ggfincke/MATH452_projects',
    liveUrl: '/assets/projects/documents/MATH_452_Midterm_Report.pdf',
  },
  {
    title: 'COVID-19 Case Surveillance Analysis',
    tagline: 'Large‑scale public health data exploration in Python.',
    collaborators: [{ name: 'Edwin Clatus' }, { name: 'Sahit Botta' }],
    dateRange: 'May 2024 - Aug 2024',
    status: 'complete',
    madeFor: 'Penn State',
    bulletPoints: [
      'End‑to‑end data science with pandas/NumPy/sklearn; multiple ML models (linear/logistic regression, SVM, KNN, trees)',
      'Final surveillance analysis project with comprehensive preprocessing, visualization, and 100% score',
    ],
    technologies: [
      'Python',
      'Machine Learning',
      'pandas',
      'NumPy',
      'scikit-learn',
      'matplotlib',
      'seaborn',
      'Jupyter',
    ],
    repoUrl: 'https://github.com/ggfincke/STAT319',
  },
  {
    title: 'BetterBettor',
    tagline: 'Decentralized sports betting dApp on Ethereum.',
    dateRange: 'Mar 2024 - May 2024',
    status: 'complete',
    madeFor: 'Penn State',
    bulletPoints: [
      'Solidity smart contracts with automated payouts and odds; MetaMask wallet integration',
      'Modern Next.js/React front‑end with real‑time betting UX',
    ],
    technologies: [
      'Solidity',
      'Next.js',
      'Ethereum',
      'Web3.js',
      'MetaMask',
      'React',
    ],
    repoUrl: 'https://github.com/ggfincke/betterbettor',
  },
  {
    title: 'SwimMate',
    tagline: 'Native iOS/watchOS swimming workout tracker.',
    dateRange: 'Feb 2024 - Jun 2024',
    status: 'in-development',
    madeFor: 'Penn State',
    featured: true,
    bulletPoints: [
      'Comprehensive swimming app to track, plan, and save workouts with history and progress visualization',
      'HealthKit + SwiftUI components for workout entry, lap timing, and analytics with Swift Charts',
      'Apple Watch companion: real‑time metrics (pace, heart rate, laps, SWOLF, calories) and workout handoff',
      'Goal‑based workouts (distance, time, calories) with real‑time feedback; pool & open‑water with GPS',
      'Achieved 100% on original submission for CMPSC 475',
    ],
    imagePath: '/assets/projects/images/swimmate.png',
    imageAlt: 'SwimMate app screenshot',
    technologies: [
      'Swift',
      'SwiftUI',
      'HealthKit',
      'WatchKit',
      'watchOS',
      'Swift Charts',
      'WatchConnectivity',
    ],
    repoUrl: 'https://github.com/ggfincke/SwimMate',
  },
  {
    title: 'OPTIMUS',
    tagline: 'Fine‑tuned Discord chatbot based on Microsoft GODEL‑v1.1.',
    dateRange: 'Feb 2024 - Apr 2024',
    status: 'complete',
    madeFor: 'Personal',
    bulletPoints: [
      'Local inference with a custom‑trained seq2seq model (HuggingFace Transformers)',
      'Rich Discord interactions, emote reactions, user triggers, and mode controls',
    ],
    technologies: [
      'Python',
      'Transformers',
      'Discord.py',
      'HuggingFace',
      'APScheduler',
    ],
    repoUrl: 'https://github.com/ggfincke/OPTIMUS',
  },
  {
    title: 'iOS Application Development Projects',
    tagline:
      'Five Swift/SwiftUI projects spanning maps, puzzles, and data‑driven apps.',
    collaborators: [{ name: 'Ashley Amendola' }],
    dateRange: 'Jan 2024 - Mar 2024',
    status: 'complete',
    madeFor: 'Penn State',
    bulletPoints: [
      'LionSpell word game, Pentominoes with drag/3D rotation, and campus map apps (SwiftUI Map + UIKit MKMapView)',
      'Pokédex with type filtering and persistence; 98% average across projects',
    ],
    technologies: [
      'Swift',
      'SwiftUI',
      'UIKit',
      'MapKit',
      'Core Data',
      'JSON',
      'Custom Shapes',
      'Gesture Handling',
      'MVC/MVVM',
      'Xcode',
    ],
  },
  {
    title: 'Memory Management & Threading in C',
    tagline: 'OS simulations for paging, scheduling, and kernel extensions.',
    collaborators: [{ name: 'Avanish Grampurohit' }],
    dateRange: 'Sep 2023 - Dec 2023',
    status: 'complete',
    madeFor: 'Penn State',
    bulletPoints: [
      'Page replacement simulator (FIFO/LRU/optimal) with demand paging',
      'Thread scheduler with cooperative & preemptive modes, round‑robin/priority, and mutex sync',
      'Kernel extensions with new syscalls and debugging tools (100% average)',
    ],
    technologies: [
      'C',
      'Systems Programming',
      'Operating Systems',
      'Memory Management',
      'Threading',
    ],
    repoUrl: 'https://github.com/ggfincke/CMPSC473_projects',
  },
  {
    title: 'USBAP',
    tagline: 'Sports‑betting data scraper for analysis and arbitrage research.',
    collaborators: [{ name: 'Yugal Kithany' }, { name: 'Kyle Lynch' }],
    dateRange: 'May 2023 - Jun 2023',
    status: 'experimental',
    madeFor: 'Personal',
    bulletPoints: [
      'Scrapes DraftKings/FanDuel markets (moneyline/spreads/totals) and normalizes for downstream analytics',
      'Foundational tooling for betting analytics and opportunity detection',
    ],
    technologies: ['Python', 'Web Scraping', 'Data Analysis', 'BeautifulSoup'],
    repoUrl: 'https://github.com/ggfincke/USBAP',
  },
  {
    title: 'MIPS Processor',
    tagline: 'Single‑cycle 32‑bit MIPS in Verilog with modular design.',
    collaborators: [{ name: 'Avanish Grampurohit' }],
    dateRange: 'Mar 2023 - May 2023',
    status: 'complete',
    madeFor: 'Penn State',
    bulletPoints: [
      'Full instruction set (arith/logic/memory/branch/jump) with Harvard organization',
      'Modular ALU, control, register file, and memory; comprehensive test coverage (100%)',
    ],
    technologies: ['Verilog', 'FPGA', 'Digital Design', 'Xilinx Vivado'],
    repoUrl: 'https://github.com/ggfincke/CMPEN331_final_project',
  },
  {
    title: 'JBOD Storage System with Caching & Network Communication',
    tagline: 'Block‑level JBOD with LFU cache and TCP client/server.',
    dateRange: 'Sep 2022 - Dec 2022',
    status: 'complete',
    madeFor: 'Penn State',
    bulletPoints: [
      'Complete JBOD storage across multiple disks with LFU caching',
      'TCP/IP client‑server architecture and robust protocol handling',
      'Full testing and integration verification (100% scores)',
    ],
    technologies: [
      'C',
      'Systems Programming',
      'Storage Systems',
      'Networking',
      'Caching',
    ],
    repoUrl: 'https://github.com/ggfincke/CMPSC311_projects',
  },
];
