// src/content/projects/skillMappings.ts
// skill-to-technology mappings w/ bidirectional semantic search

export const skillMappings: Record<string, string[]> = {
  // languages
  python: ['python'],
  swift: ['swift'],
  c: ['c'],
  'c/c++': ['c/c++', 'c'],
  go: ['go'],
  javascript: ['javascript', 'typescript'],
  'javascript (es6+)': ['javascript', 'typescript'],
  typescript: ['typescript', 'javascript'],
  java: ['java'],
  sql: ['sql', 'sqlite', 'postgresql'],
  solidity: ['solidity'],
  verilog: ['verilog'],

  // frontend frameworks
  react: ['react', 'next.js'],
  'next.js': ['next.js', 'react'],
  'react router': ['react router'],
  'tailwind css': ['tailwind css'],
  html5: ['html', 'html5'],
  css3: ['css', 'css3'],
  swiftui: ['swiftui'],
  uikit: ['uikit'],

  // backend frameworks
  'node.js': ['node.js'],
  django: ['django'],
  'django rest framework': ['django rest framework', 'django'],
  fastapi: ['fastapi'],
  celery: ['celery'],
  'rest apis': ['rest apis'],
  'spring boot': ['spring boot'],
  'spring data jpa': ['spring data jpa', 'spring boot'],
  'spring security': ['spring security', 'spring boot'],
  'spring batch': ['spring batch', 'spring boot'],
  actuator: ['actuator', 'spring boot'],

  // databases
  postgresql: ['postgresql'],
  pgvector: ['pgvector', 'postgresql'],
  sqlite: ['sqlite'],
  supabase: ['supabase'],
  firebase: ['firebase'],
  redis: ['redis'],
  h2: ['h2'],

  // mobile platforms
  ios: ['ios', 'swiftui', 'uikit'],
  watchos: ['watchos'],
  healthkit: ['healthkit'],
  watchkit: ['watchkit'],
  watchconnectivity: ['watchconnectivity'],
  mapkit: ['mapkit'],
  'core data': ['core data'],
  'swift charts': ['swift charts'],

  // AI/ML libraries
  pytorch: ['pytorch'],
  tensorflow: ['tensorflow', 'keras'],
  keras: ['keras', 'tensorflow'],
  'scikit-learn': ['scikit-learn'],
  huggingface: ['huggingface', 'transformers'],
  'hugging face transformers': ['huggingface', 'transformers'],
  openai: ['openai'],
  'openai api': ['openai'],
  'anthropic claude': ['anthropic claude', 'anthropic'],
  'anthropic claude api': ['anthropic claude', 'anthropic'],
  anthropic: ['anthropic', 'anthropic claude'],
  ollama: ['ollama'],
  pandas: ['pandas'],
  numpy: ['numpy'],
  matplotlib: ['matplotlib'],
  seaborn: ['seaborn'],
  jupyter: ['jupyter'],
  'deep learning': ['deep learning', 'tensorflow', 'keras', 'pytorch', 'cnn'],
  resnet: ['resnet'],
  densenet: ['densenet'],
  'random fourier features': ['random fourier features'],
  gemini: ['gemini'],
  mistral: ['mistral'],
  'lm studio': ['lm studio'],
  'machine learning': ['machine learning', 'scikit-learn', 'deep learning'],
  cnn: ['cnn', 'deep learning'],

  // devops & tools
  'github actions': ['github actions'],
  'ci/cd (github actions)': ['github actions', 'ci/cd'],
  'ci/cd': ['ci/cd', 'github actions'],
  docker: ['docker'],
  'docker compose': ['docker compose', 'docker'],
  microservices: ['microservices'],
  vite: ['vite'],
  'vs code': ['vs code'],
  'vs code extension api': ['vs code extension api'],
  xcode: ['xcode'],
  figma: ['figma'],
  latex: ['latex'],
  typst: ['typst'],
  mdx: ['mdx'],
  shiki: ['shiki'],
  katex: ['katex'],
  mermaid: ['mermaid'],
  rich: ['rich'],
  eslint: ['eslint'],
  prettier: ['prettier'],
  gradle: ['gradle'],
  flyway: ['flyway'],
  esbuild: ['esbuild'],
  vitest: ['vitest'],
  comlink: ['comlink'],
  git: ['git'],
  'git hooks': ['git hooks'],
  'lighthouse ci': ['lighthouse ci'],

  // web3 & blockchain
  'web3.js': ['web3.js'],
  metamask: ['metamask'],
  'blockchain development': ['solidity', 'ethereum', 'web3.js'],
  cnns: ['cnn', 'deep learning'],
  ethereum: ['ethereum', 'solidity', 'web3.js'],

  // cloud & infra
  aws: ['aws', 'ec2', 'ssm', 'cloudwatch', 's3'],
  ec2: ['ec2', 'aws'],
  ssm: ['ssm', 'aws'],
  cloudwatch: ['cloudwatch', 'aws'],
  s3: ['s3', 'aws'],
  jwt: ['jwt'],
  rcon: ['rcon'],

  // systems & architecture
  'operating systems': ['operating systems'],
  'computer architecture': ['computer architecture'],
  'storage systems': ['storage systems'],
  'memory management': ['memory management'],
  threading: ['threading'],
  'systems programming': ['systems programming'],
  networking: ['networking'],
  caching: ['caching'],
  simplescalar: ['simplescalar'],
  'cache hierarchies': ['cache hierarchies'],
  'branch prediction': ['branch prediction'],
  'performance analysis': ['performance analysis'],

  // hardware
  fpga: ['fpga'],
  'xilinx vivado': ['xilinx vivado'],
  'digital design': ['digital design'],

  // specialized
  selenium: ['selenium'],
  'web scraping (selenium, beautifulsoup)': [
    'selenium',
    'beautifulsoup',
    'web scraping',
  ],
  beautifulsoup: ['beautifulsoup'],
  typer: ['typer'],
  'cli development (typer)': ['typer', 'cli'],
  'discord.py': ['discord.py'],
  'bots (discord.py)': ['discord.py'],
  'discord.js': ['discord.js'],
  'captcha solving': ['captcha solving'],
  'data analysis': ['data analysis', 'pandas', 'numpy'],
  cli: ['cli'],
  json: ['json'],
  docx: ['docx'],
  apscheduler: ['apscheduler'],
  'custom shapes': ['custom shapes'],
  'gesture handling': ['gesture handling'],
  'mvc/mvvm': ['mvc/mvvm'],
  transformers: ['transformers', 'huggingface'],
  'web scraping': ['selenium', 'beautifulsoup', 'web scraping'],
};
